[package]
name = "rlox"
version = "0.1.0"
authors = ["Caranatar <caranatar@riseup.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
color-eyre = "0.5.10"
float-cmp = "0.8.0"
rustyline = "7.0.0"
slurp = "1.0.1"
